version: "3.9"
services:
  backend:
    build:
      context: ../backend
    container_name: backend
    ports: 
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../.env
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DN: expense_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ../.env
  frontend:
    container_name: frontend
    build: 
      context: ../frontend
    volumes:
      - ../frontend/smart-expense-tracker:/app
    ports:
      - "5173:5173"
    env_file:
      - ../.env
    working_dir: /app
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

    

volumes:
  pgdata: